apiVersion: v1
kind: ResourceQuota
metadata:
  name: gpp-default-quota
  namespace: {{NAMESPACE}}
spec:
  hard:
    # リソース上限（例。後で調整）
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi

    pods: "20"
    services: "10"
    configmaps: "50"
    secrets: "50"
    persistentvolumeclaims: "5"
